apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: Deployment-demo
    project: roboshop 
    app: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: Deployment-demo
    project: roboshop 
    app: nginx
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: {{ .Values.service.targetPort }} #container port